services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: todo_db
      POSTGRES_USER: todo_user
      POSTGRES_PASSWORD: todo_pass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - todo-net

  migrator:
    build:
      context: .
      dockerfile: backend/Dockerfile
      target: build
    depends_on:
      - db
    environment:
      ConnectionStrings__DefaultConnection: Host=db;Port=5432;Database=todo_db;Username=todo_user;Password=todo_pass
    entrypoint: ["dotnet", "ef", "database", "update"]
    networks:
      - todo-net

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    depends_on:
      - db
      - migrator
    ports:
      - "8080:8080"
    environment:
      ConnectionStrings__DefaultConnection: Host=db;Port=5432;Database=todo_db;Username=todo_user;Password=todo_pass
    networks:
      - todo-net

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - todo-net

volumes:
  pgdata:

networks:
  todo-net: